#ifndef __MUPCONFIG_H_1046__
#define __MUPCONFIG_H_1046__

#define COPYRIGHT_DECLARE \
"//\n\
//\n\
//    This software is provided 'as-is', without any express or implied\n\
//    warranty. In no event will the authors be held liable for any\n\
//    damages arising from the use of this software.\n\
//\n\
//    Generated by mupcompiler.\n\
//\n\
//    Author: muidea@gmail.com\n\
//\n\
//\n"

#define PRODUCT_DECLARE \
"Power by mupcompiler."

#define VERSION_DECLARE \
"Version: v1.0.0"

#define BUILD_TIME_DECLARE \
"Build: 2016-02-24 10:46:16"

#define AUTHOR_DECLARE \
"Author: muidea@gmail.com"

#endif

